package_rename_config:
  android:
    app_name: HZN Gyms
    package_name: com.hzngyms.app

  ios:
    app_name: HZN Gyms
    bundle_name: com.hzngyms.app
    package_name: com.hzngyms.app

  linux:
    app_name: HZN Gyms
    package_name: com.hzngyms.app
    exe_name: hzn_gyms

  macos:
    app_name: HZN Gyms
    package_name: com.hzngyms.app
    copyright_notice: HZN Gyms

  web:
    app_name: HZN Gyms
    short_app_name: HZN Gyms
    description: HZN Gyms

  windows:
    app_name: HZN Gyms
    organization: HZN Gyms
    copyright_notice: HZN Gyms
    exe_name: hzn_gyms
