/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("pbc_3841632486")

  // update collection data
  unmarshal({
    "authAlert": {
      "emailTemplate": {
        "body": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <meta charset=\"UTF-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n  <title>New login alert</title>\r\n</head>\r\n<body style=\"margin:0;padding:0;background-color:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827;\">\r\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color:#F3F4F6;padding:24px 12px;\">\r\n    <tr>\r\n      <td align=\"center\">\r\n        <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;background-color:#FFFFFF;border-radius:12px;overflow:hidden;border:1px solid #E5E7EB;\">\r\n          <tr>\r\n            <td style=\"background-color:#0B0B0B;padding:20px 24px;border-bottom:3px solid #22C55E;\">\r\n              <p style=\"margin:0;font-size:18px;font-weight:bold;color:#FFFFFF;letter-spacing:0.02em;\">HZN Gyms</p>\r\n              <p style=\"margin:4px 0 0;font-size:12px;color:#9CA3AF;\">HZN systems</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:28px 24px;\">\r\n              <h1 style=\"margin:0 0 12px;font-size:22px;line-height:1.3;color:#111827;\">New login to your account</h1>\r\n              <p style=\"margin:0 0 16px;font-size:15px;line-height:1.5;color:#374151;\">We noticed a login to your {APP_NAME} account from a new location:</p>\r\n              <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin:0 0 20px;\">\r\n                <tr>\r\n                  <td style=\"background-color:#F9FAFB;border:1px solid #E5E7EB;border-radius:10px;padding:16px;\">\r\n                    <p style=\"margin:0;font-size:14px;line-height:1.5;color:#111827;font-style:italic;\">{ALERT_INFO}</p>\r\n                  </td>\r\n                </tr>\r\n              </table>\r\n              <p style=\"margin:0 0 8px;font-size:14px;line-height:1.5;color:#111827;\"><strong>If this wasn't you,</strong> change your {APP_NAME} password immediately to revoke access from other locations.</p>\r\n              <p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7280;\">If this was you, you can disregard this email.</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:16px 24px 24px;border-top:1px solid #F3F4F6;\">\r\n              <p style=\"margin:0;font-size:12px;color:#9CA3AF;\">Thanks,<br/>The {APP_NAME} team</p>\r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </td>\r\n    </tr>\r\n  </table>\r\n</body>\r\n</html>",
        "subject": "New login to your {APP_NAME} account"
      },
      "enabled": true
    },
    "confirmEmailChangeTemplate": {
      "body": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <meta charset=\"UTF-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n  <title>Confirm your new email</title>\r\n</head>\r\n<body style=\"margin:0;padding:0;background-color:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827;\">\r\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color:#F3F4F6;padding:24px 12px;\">\r\n    <tr>\r\n      <td align=\"center\">\r\n        <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;background-color:#FFFFFF;border-radius:12px;overflow:hidden;border:1px solid #E5E7EB;\">\r\n          <tr>\r\n            <td style=\"background-color:#0B0B0B;padding:20px 24px;border-bottom:3px solid #22C55E;\">\r\n              <p style=\"margin:0;font-size:18px;font-weight:bold;color:#FFFFFF;letter-spacing:0.02em;\">HZN Gyms</p>\r\n              <p style=\"margin:4px 0 0;font-size:12px;color:#9CA3AF;\">HZN systems</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:28px 24px;\">\r\n              <h1 style=\"margin:0 0 12px;font-size:22px;line-height:1.3;color:#111827;\">Confirm your new email</h1>\r\n              <p style=\"margin:0 0 24px;font-size:15px;line-height:1.5;color:#374151;\">Confirm this address to finish updating your {APP_NAME} account email.</p>\r\n              <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin:0 0 24px;\">\r\n                <tr>\r\n                  <td align=\"center\" bgcolor=\"#22C55E\" style=\"border-radius:8px;\">\r\n                    <a href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display:inline-block;padding:14px 22px;font-size:15px;font-weight:bold;color:#0B0B0B;text-decoration:none;\">Confirm new email</a>\r\n                  </td>\r\n                </tr>\r\n              </table>\r\n              <p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7280;\">If you did not ask to change your email, you can ignore this message.</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:16px 24px 24px;border-top:1px solid #F3F4F6;\">\r\n              <p style=\"margin:0;font-size:12px;color:#9CA3AF;\">Thanks,<br/>The {APP_NAME} team</p>\r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </td>\r\n    </tr>\r\n  </table>\r\n</body>\r\n</html>",
      "subject": "Confirm your new {APP_NAME} email"
    },
    "otp": {
      "emailTemplate": {
        "body": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <meta charset=\"UTF-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n  <title>Your login code</title>\r\n</head>\r\n<body style=\"margin:0;padding:0;background-color:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827;\">\r\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color:#F3F4F6;padding:24px 12px;\">\r\n    <tr>\r\n      <td align=\"center\">\r\n        <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;background-color:#FFFFFF;border-radius:12px;overflow:hidden;border:1px solid #E5E7EB;\">\r\n          <tr>\r\n            <td style=\"background-color:#0B0B0B;padding:20px 24px;border-bottom:3px solid #22C55E;\">\r\n              <p style=\"margin:0;font-size:18px;font-weight:bold;color:#FFFFFF;letter-spacing:0.02em;\">HZN Gyms</p>\r\n              <p style=\"margin:4px 0 0;font-size:12px;color:#9CA3AF;\">HZN systems</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:28px 24px;\">\r\n              <h1 style=\"margin:0 0 12px;font-size:22px;line-height:1.3;color:#111827;\">Your login code</h1>\r\n              <p style=\"margin:0 0 20px;font-size:15px;line-height:1.5;color:#374151;\">Use this code to sign in to {APP_NAME}. It expires soon.</p>\r\n              <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin:0 0 20px;\">\r\n                <tr>\r\n                  <td align=\"center\" style=\"background-color:#F9FAFB;border:1px solid #E5E7EB;border-radius:10px;padding:20px;\">\r\n                    <p style=\"margin:0;font-size:36px;letter-spacing:0.28em;font-weight:bold;color:#0B0B0B;font-family:Consolas,Monaco,monospace;\">{OTP}</p>\r\n                  </td>\r\n                </tr>\r\n              </table>\r\n              <p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7280;\">If you did not request this code, you can ignore this email.</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:16px 24px 24px;border-top:1px solid #F3F4F6;\">\r\n              <p style=\"margin:0;font-size:12px;color:#9CA3AF;\">Thanks,<br/>The {APP_NAME} team</p>\r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </td>\r\n    </tr>\r\n  </table>\r\n</body>\r\n</html>"
      }
    },
    "resetPasswordTemplate": {
      "body": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <meta charset=\"UTF-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n  <title>Reset your password</title>\r\n</head>\r\n<body style=\"margin:0;padding:0;background-color:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827;\">\r\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color:#F3F4F6;padding:24px 12px;\">\r\n    <tr>\r\n      <td align=\"center\">\r\n        <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;background-color:#FFFFFF;border-radius:12px;overflow:hidden;border:1px solid #E5E7EB;\">\r\n          <tr>\r\n            <td style=\"background-color:#0B0B0B;padding:20px 24px;border-bottom:3px solid #22C55E;\">\r\n              <p style=\"margin:0;font-size:18px;font-weight:bold;color:#FFFFFF;letter-spacing:0.02em;\">HZN Gyms</p>\r\n              <p style=\"margin:4px 0 0;font-size:12px;color:#9CA3AF;\">HZN systems</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:28px 24px;\">\r\n              <h1 style=\"margin:0 0 12px;font-size:22px;line-height:1.3;color:#111827;\">Reset your password</h1>\r\n              <p style=\"margin:0 0 24px;font-size:15px;line-height:1.5;color:#374151;\">We received a request to reset your {APP_NAME} password. Click below to choose a new one.</p>\r\n              <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin:0 0 24px;\">\r\n                <tr>\r\n                  <td align=\"center\" bgcolor=\"#22C55E\" style=\"border-radius:8px;\">\r\n                    <a href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display:inline-block;padding:14px 22px;font-size:15px;font-weight:bold;color:#0B0B0B;text-decoration:none;\">Reset password</a>\r\n                  </td>\r\n                </tr>\r\n              </table>\r\n              <p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7280;\">If you did not ask to reset your password, you can ignore this email.</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:16px 24px 24px;border-top:1px solid #F3F4F6;\">\r\n              <p style=\"margin:0;font-size:12px;color:#9CA3AF;\">Thanks,<br/>The {APP_NAME} team</p>\r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </td>\r\n    </tr>\r\n  </table>\r\n</body>\r\n</html>"
    },
    "verificationTemplate": {
      "body": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <meta charset=\"UTF-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n  <title>Verify your email</title>\r\n</head>\r\n<body style=\"margin:0;padding:0;background-color:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827;\">\r\n  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color:#F3F4F6;padding:24px 12px;\">\r\n    <tr>\r\n      <td align=\"center\">\r\n        <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:560px;background-color:#FFFFFF;border-radius:12px;overflow:hidden;border:1px solid #E5E7EB;\">\r\n          <tr>\r\n            <td style=\"background-color:#0B0B0B;padding:20px 24px;border-bottom:3px solid #22C55E;\">\r\n              <p style=\"margin:0;font-size:18px;font-weight:bold;color:#FFFFFF;letter-spacing:0.02em;\">HZN Gyms</p>\r\n              <p style=\"margin:4px 0 0;font-size:12px;color:#9CA3AF;\">HZN systems</p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:28px 24px;\">\r\n              <h1 style=\"margin:0 0 12px;font-size:22px;line-height:1.3;color:#111827;\">Verify your email</h1>\r\n              <p style=\"margin:0 0 24px;font-size:15px;line-height:1.5;color:#374151;\">Thanks for joining {APP_NAME}. Confirm your email address to continue.</p>\r\n              <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin:0 0 24px;\">\r\n                <tr>\r\n                  <td align=\"center\" bgcolor=\"#22C55E\" style=\"border-radius:8px;\">\r\n                    <a href=\"{APP_URL}/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\" style=\"display:inline-block;padding:14px 22px;font-size:15px;font-weight:bold;color:#0B0B0B;text-decoration:none;\">Verify email</a>\r\n                  </td>\r\n                </tr>\r\n              </table>\r\n              <p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7280;\">If the button does not work, open this link:<br/><a href=\"{APP_URL}/confirm-verification/{TOKEN}\" style=\"color:#16A34A;word-break:break-all;\">{APP_URL}/confirm-verification/{TOKEN}</a></p>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td style=\"padding:16px 24px 24px;border-top:1px solid #F3F4F6;\">\r\n              <p style=\"margin:0;font-size:12px;color:#9CA3AF;\">Thanks,<br/>The {APP_NAME} team</p>\r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </td>\r\n    </tr>\r\n  </table>\r\n</body>\r\n</html>",
      "subject": "Verify your {APP_NAME} email"
    }
  }, collection)

  return app.save(collection)
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_3841632486")

  // update collection data
  unmarshal({
    "authAlert": {
      "emailTemplate": {
        "body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Login from a new location"
      },
      "enabled": false
    },
    "confirmEmailChangeTemplate": {
      "body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
      "subject": "Confirm your {APP_NAME} new email address"
    },
    "otp": {
      "emailTemplate": {
        "body": "<p>Hello,</p><p>Your one-time login code is: <strong>{OTP}</strong></p><p>This code expires in 5 minutes.</p><p><i>If you did not request this, you can ignore this email.</i></p><p>Thanks,<br/>{APP_NAME} team</p>"
      }
    },
    "resetPasswordTemplate": {
      "body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
    },
    "verificationTemplate": {
      "body": "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Verify Your Email</title>\n  <style>\n    body {\n      font-family: Arial, sans-serif;\n      background-color: #f4f4f4;\n      color: #333;\n      margin: 0;\n      padding: 20px;\n    }\n    .container {\n      background-color: #ffffff;\n      padding: 20px;\n      max-width: 600px;\n      margin: auto;\n      border-radius: 8px;\n      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n    }\n    .btn {\n      display: inline-block;\n      background-color: #007bff;\n      color: #ffffff;\n      padding: 12px 20px;\n      text-decoration: none;\n      font-weight: bold;\n      border-radius: 5px;\n    }\n    .footer {\n      font-size: 12px;\n      color: #777;\n      margin-top: 20px;\n    }\n  </style>\n</head>\n<body>\n\n  <div class=\"container\">\n    <h2>Hello,</h2>\n    <p>Thank you for signing up with <strong>{APP_NAME}</strong>!</p>\n    <p>To complete your registration, please verify your email address by clicking the button below:</p>\n\n    <p style=\"text-align: center;\">\n      <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify Email</a>\n    </p>\n\n    <p>If the button above does not work, you can also copy and paste the following link into your browser:</p>\n    <p><a href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\">{APP_URL}/_/#/auth/confirm-verification/{TOKEN}</a></p>\n\n    <p>Thank you,</p>\n    <p>The {APP_NAME} Team</p>\n\n    <div class=\"footer\">\n      <p>If you did not sign up for {APP_NAME}, please ignore this email.</p>\n      <p>&copy; 2025 {APP_NAME}. All rights reserved.</p>\n    </div>\n  </div>\n\n</body>\n</html>\n",
      "subject": "Welcome to {APP_NAME}! Please confirm your email"
    }
  }, collection)

  return app.save(collection)
})
